services:
  web:
    container_name: myweb
    build:
      context: chore-wheel-web
    networks:
      - webapi
    ports:
      - 3000:3000
  api:
    container_name: myapi
    build:
      context: chore-wheel-api
    networks:
      - webapi
      - dbapi
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.5
    restart: always
    networks:
      - dbapi
    volumes:
      - ./chore-wheel-api/Database/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
      - db-data2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chore_wheel
      - POSTGRES_PASSWORD=wheel
      - POSTGRES_USER=wheel
    expose:
      - 5432

volumes:
  db-data2:
networks:
  webapi:
  dbapi:
